services:
    sitemap_gz_dumper:
        class:      KPhoen\SitemapBundle\Dumper\GzFileDumper
        arguments:  [ %kernel.root_dir%/../web/sitemap.xml.gz ]

    sitemap_xml_formatter:
        class:      KPhoen\SitemapBundle\Formatter\XmlFormatter

    sitemap:
        class:      KPhoen\SitemapBundle\Sitemap\Sitemap
        arguments:  [ @sitemap_gz_dumper, @sitemap_xml_formatter, %sitemap.config.base_host%, %sitemap.config.base_host_sitemap%, %sitemap.config.limit% ]
